artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/18448bca58594340be80da2ee65ead8a/artifacts
end_time: 1783849342832
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 18448bca58594340be80da2ee65ead8a
run_name: Logistic Regression
source_name: ''
source_type: 4
source_version: ''
start_time: 1783849339594
status: 4
tags: []
user_id: rajes
