artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/92798ce7c1b44450a1ab7da2b3344ba1/artifacts
end_time: 1783850892601
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 92798ce7c1b44450a1ab7da2b3344ba1
run_name: RandomForest_GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1783850878495
status: 3
tags: []
user_id: rajes
