artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/f6e25bffe82c404d878f553665d793e6/artifacts
end_time: 1783850873483
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: f6e25bffe82c404d878f553665d793e6
run_name: Gradient Boosting
source_name: ''
source_type: 4
source_version: ''
start_time: 1783850868154
status: 3
tags: []
user_id: rajes
