apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-disease-api
  namespace: mlops
  labels:
    app: heart-disease-api
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-disease-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: heart-disease-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: api
          image: heart-disease-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "models/best_model.joblib"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 30
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
              readOnly: true
      volumes:
        - name: model-storage
          configMap:
            name: model-configmap
