artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/0ac512b56f88429ebdde01b62a854232/artifacts
end_time: 1783864644192
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 0ac512b56f88429ebdde01b62a854232
run_name: RandomForest_GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1783864620638
status: 3
tags: []
user_id: rajes
