artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/6ba601d1133c4dbe906da2322288d6cb/artifacts
end_time: 1783864729765
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 6ba601d1133c4dbe906da2322288d6cb
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1783864719064
status: 3
tags: []
user_id: rajes
