artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/d4aff88cc8434f9fa94680b2caf76dee/artifacts
end_time: 1783851403581
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: d4aff88cc8434f9fa94680b2caf76dee
run_name: Random Forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1783851397153
status: 3
tags: []
user_id: rajes
