artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/bedfccabfd584cd88389058c12805f84/artifacts
end_time: 1783864707695
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: bedfccabfd584cd88389058c12805f84
run_name: Random Forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1783864696118
status: 3
tags: []
user_id: rajes
