artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/a5aff05c8d39457097f22285f3f45fa1/artifacts
end_time: 1783849476049
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: a5aff05c8d39457097f22285f3f45fa1
run_name: Random Forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1783849469033
status: 3
tags: []
user_id: rajes
