artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/1ff43fc4fc6c4f86b74a6bce7523d16b/artifacts
end_time: 1783864004297
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 1ff43fc4fc6c4f86b74a6bce7523d16b
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1783863993399
status: 3
tags: []
user_id: rajes
