artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/ecd1f27ba3484c26a1a8fa6cca1a3e71/artifacts
end_time: 1783849417121
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: ecd1f27ba3484c26a1a8fa6cca1a3e71
run_name: SVM
source_name: ''
source_type: 4
source_version: ''
start_time: 1783849411298
status: 3
tags: []
user_id: rajes
