artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/7ab719f584124f248ed10bac9e87379e/artifacts
end_time: 1783851174823
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 7ab719f584124f248ed10bac9e87379e
run_name: Random Forest
source_name: ''
source_type: 4
source_version: ''
start_time: 1783851168418
status: 3
tags: []
user_id: rajes
