artifact_uri: file:D:/MyFiles/BITS/MTech/SEMESTER-3/MLOPS/Assignments/1/MLOPS_Assignment/mlruns/194442037159289122/97fe161278a14c8988b24dcfbbae2d63/artifacts
end_time: 1783851430036
entry_point_name: ''
experiment_id: '194442037159289122'
lifecycle_stage: active
run_id: 97fe161278a14c8988b24dcfbbae2d63
run_name: RandomForest_GridSearch
source_name: ''
source_type: 4
source_version: ''
start_time: 1783851415635
status: 3
tags: []
user_id: rajes
