apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heart-disease.fullname" . }}
  labels:
    {{- include "heart-disease.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "heart-disease.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "heart-disease.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "{{ .Values.monitoring.prometheus.scrape }}"
        prometheus.io/path: "{{ .Values.monitoring.prometheus.path }}"
        prometheus.io/port: "{{ .Values.monitoring.prometheus.port }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: MODEL_PATH
              value: {{ .Values.env.MODEL_PATH }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 20
            periodSeconds: 30
